version: '3.8'

services:
  calculator-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator-container
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/data        
      - ./logs:/app/logs          
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key
      - CONTAINER_MODE=true
      - CONTAINER_USERNAME=user
      - CONTAINER_PASSWORD=user123
    stdin_open: true
    tty: true

volumes:
  db_data:
